name: Actionlint

on:
  pull_request:
    branches: '*'
  push:
  workflow_dispatch:

jobs:
  checkout:
    runs-on:
      - Linux
    steps:
      - uses: actions/checkout@v2
      - uses: devops-actions/actionlint@v0.1.2
