name: Version Demo
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        required: true
        default: '2'
      minor:
        description: 'Minor version'
        required: true
        default: '3'
      patch:
        description: 'Patch version'
        required: true
        default: '3'

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      MAJOR: ${{ github.event.inputs.major }}
      MINOR: ${{ github.event.inputs.minor }}
      PATCH: ${{ github.event.inputs.patch }}
      VERSION_DOT: ${{ format('{0}.{1}.{2}', github.event.inputs.major, github.event.inputs.minor, github.event.inputs.patch) }}
      VERSION_UNDERSCORE: ${{ format('{0}_{1}_{2}', github.event.inputs.major, github.event.inputs.minor, github.event.inputs.patch) }}
    steps:
      - name: Show versions
        run: |
          echo "Dotted: $VERSION_DOT"
          echo "Underscored: $VERSION_UNDERSCORE"
          echo "Inline dot:  ${{ format('{0}.{1}.{2}', github.event.inputs.major, github.event.inputs.minor, github.event.inputs.patch) }}"
          echo "Inline under:${{ format('{0}_{1}_{2}', github.event.inputs.major, github.event.inputs.minor, github.event.inputs.patch) }}"
