name: Version Demo
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MAJOR: '2'
  MINOR: '3'
  PATCH: '3'
  VERSION_PARTS: '["${{ env.MAJOR }}","${{ env.MINOR }}","${{ env.PATCH }}"]'
  VERSION_UNDERSCORE: ${{ join(fromJson(env.VERSION_PARTS), '_') }}
  VERSION_DOT: ${{ join(fromJson(env.VERSION_PARTS), '.') }}

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Show both versions
        run: |
          echo "Underscored: $VERSION_UNDERSCORE"
          echo "Dotted: $VERSION_DOT"
          echo "Inline underscore: ${{ join(fromJson(env.VERSION_PARTS), '_') }}"
          echo "Inline dot: ${{ join(fromJson(env.VERSION_PARTS), '.') }}"
