name: Version Demo
on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  MAJOR: '2'
  MINOR: '3'
  PATCH: '3'
  VERSION_UNDERSCORE: ${{ join([ env.MAJOR, env.MINOR, env.PATCH ], '_' ) }}
  VERSION_DOT: ${{ join([ env.MAJOR, env.MINOR, env.PATCH ], '.' ) }}

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Show both versions
        run: |
          echo "Underscored: $VERSION_UNDERSCORE"
          echo "Dotted:      $VERSION_DOT"
          echo "Underscored in-line: ${{ join([ env.MAJOR, env.MINOR, env.PATCH ], '_' ) }}"
